site_name: Status System
site_url: https://status-system.juliankorgol.com
theme:
  name: material
  icon:
    annotation: material/arrow-right-circle
  features:
    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search
  - privacy

markdown_extensions:
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

#extra:
#  consent:
#    title: Cookie consent
#    description: >-
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better.
